
pre-init:
  stage: pre-init
  only:
    refs:
      - develop
  variables:
    VARS_FILE: vars/apps.tfvars.json
  before_script:
    #- cd ${ASSET_NAME}
  artifacts:
    paths:
      #- ${ASSET_NAME}/${WORKSPACE}.tfplan

validate:
  stage: validate
  script:
    - terraform init -input=false
    # - terraform workspace select ${WORKSPACE} || terraform workspace new ${WORKSPACE}
    - terraform validate -json

