image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${WORKSPACE}
  WORKSPACE: qual
  VARS_FILE: vars/vars.tfvars.json

cache:
  key: ${WORKSPACE}
  paths:
    - ${TF_ROOT}/.terraform

##########################################################
init:
  stage: init

  only:
    refs:
      - test

  before_script:
    - terraform --version
    - terraform --help
    - gitlab-terraform --help
    - terraform workspace new ciao

  script:
    - gitlab-terraform init -var-file=${VARS_FILE}
    - gitlab-terraform validate -json

##########################################################
plan:
  stage: plan

  dependencies:
    - init

  only:
    refs:
      - test

  before_script:
    - terraform --version
    - mkdir ~/.ssh
    - cp $raspberry_config ~/.ssh/config
    - cp $raspberry_key ~/.ssh/raspberry_key
    - chmod 0600 ~/.ssh/raspberry_key

  script:
    - gitlab-terraform plan -input=false -var="raspberry_host=$raspberry_host"
    - gitlab-terraform plan-json

  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache

    reports:
      terraform: ${TF_ROOT}/${WORKSPACE}/plan.json

##########################################################
apply:
  stage: apply

  dependencies:
    - plan

  only:
    refs:
      - test

  before_script:
    - mkdir ~/.ssh
    - cp $raspberry_config ~/.ssh/config
    - cp $raspberry_key ~/.ssh/raspberry_key
    - chmod 0600 ~/.ssh/raspberry_key

  script:
    - gitlab-terraform apply
