job 0:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

  stage: validate

  only:
    refs:
      - test

  variables:
    WORKSPACE: qual
    VARS_FILE: vars/vars.tfvars.json

  before_script:
    - terraform --version

  script:
    - echo "$VARIABLE_TEST"
    - echo "$VARIABLE_TEST_FILE"
    - terraform init -input=false -var-file=${VARS_FILE}
    - terraform workspace new ${WORKSPACE} || terraform workspace select ${WORKSPACE}
    - terraform validate -json

job 1:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

  stage: plan

  only:
    refs:
      - test

  variables:
    WORKSPACE: qual
    VARS_FILE: vars/vars.tfvars.json

  before_script:
    - terraform --version
    - mkdir .ssh
    - cd .ssh
    - cp $raspberry_key raspberry_key
    - chmod 0600 raspberry_key
    - cat $raspberry_config

  script:
    - terraform init -input=false
    - terraform workspace new ${WORKSPACE} || terraform workspace select ${WORKSPACE}
    - terraform plan -input=false -out=${WORKSPACE}.tfplan -var="raspberry_host=$raspberry_host"

  artifacts:
    paths:
      - ${WORKSPACE}.tfplan
