job 0:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: prepare
  only:
    refs:
      - test
  variables:
    WORKSPACE: qual
    VARS_FILE: vars/vars.tfvars.json

  before_script:
    - terraform --version
  script:
    - echo "$VARIABLE_TEST"
    - echo "$VARIABLE_TEST_FILE"
    - terraform providers
    - terraform init -input=false -var-file=${VARS_FILE}
    - terraform workspace select ${WORKSPACE} || terraform workspace new ${WORKSPACE}
    #- terraform validate -json