image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${WORKSPACE}
  VARS_FILE: ./vars/vars.json
  PORTS_FILE: ${SERVICES_PORTS}

cache:
  key: ${WORKSPACE}
  paths:
    - ${TF_ROOT}/.terraform


##########################################################
qual:init:
  stage: init

  only:
    refs:
      - test

  variables:
    WORKSPACE: qual

  before_script:
    - terraform --version

  script:
    - gitlab-terraform init -var-file=${VARS_FILE} -var-file=${PORTS_FILE} -var="workspace=${WORKSPACE}"
    - gitlab-terraform validate -json

###########################################################
qual:plan:
  stage: plan

  dependencies:
    - qual:init

  variables:
    WORKSPACE: qual

  only:
    refs:
      - test

  before_script:
    - mkdir ~/.ssh
    - cp $raspberry_config ~/.ssh/config
    - cp $raspberry_key ~/.ssh/raspberry_key
    - chmod 0600 ~/.ssh/raspberry_key

  script:
    - gitlab-terraform plan -input=false -var="raspberry_host=$raspberry_host" -var="workspace=${WORKSPACE}" -var-file=${PORTS_FILE}
    - gitlab-terraform plan-json

  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache

    reports:
      terraform: ${TF_ROOT}/${WORKSPACE}/plan.json

###########################################################
qual:apply:
  stage: apply

  dependencies:
    - qual:plan

  variables:
    WORKSPACE: qual

  only:
    refs:
      - test

  before_script:
    - mkdir ~/.ssh
    - cp $raspberry_config ~/.ssh/config
    - cp $raspberry_key ~/.ssh/raspberry_key
    - chmod 0600 ~/.ssh/raspberry_key

  script:
    - gitlab-terraform apply
